.github/ISSUE_TEMPLATE/chore-issue-template.md, .github/ISSUE_TEMPLATE/ci-issue-template.md, .github/ISSUE_TEMPLATE/docs-issue-template.md, .github/ISSUE_TEMPLATE/epic-issue-template.md, .github/ISSUE_TEMPLATE/fix-issue-template.md, .github/ISSUE_TEMPLATE/performance-issue-template.md, .github/ISSUE_TEMPLATE/standard-issue.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- updated standard issue template
- added epic issue template
=> chore: 🔧 update issue templates

.azuredevops/pipelines/deploy-to-cdn.yml, .azuredevops/pipelines/templates/push-to-storage-feature.template.yml, .azuredevops/pipelines/templates/push-to-storage-main.template.yml
- resolve nested templates to prevent empty variables
- add code comments
=> ci: fix feature branch deployment pipeline

.github/ISSUE_TEMPLATE/chore-issue-template.md, .github/ISSUE_TEMPLATE/ci-issue-template.md, .github/ISSUE_TEMPLATE/docs-issue-template.md, .github/ISSUE_TEMPLATE/feature-issue-template.md, .github/ISSUE_TEMPLATE/test-issue-template.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
refator existing templates and add a new test-issue template
=> chore: update-issue-templates

CONTRIBUTING.md, packages/components/docs/release-guide.md
added information on how to use feature branch deployments and the limitations due to versioning.
closes https://github.com/solid-design-system/internal/issues/12
=> docs: add info for feature branch deployments

CONTRIBUTING.md
I slightly changed the "How we work" section. I actually wanted it to be all "We..."-sentences, but couldn´t find a way to formulate "Development closely works with Design." that way.
I added the usage of tokens and the optimization for accessibility to our dev guidelines, because I think they are important topics.
=> docs: 📚 Adding tokens and a11y to CONTRIBUTING.md

packages/components/src/components/button/button.ts, packages/tokens/src/create-theme.cjs, packages/tokens/src/tokens.json
In addition to the tokens, we have to update button and accordion that it matches the new a11y concept:
@coraliefeil @van-nguyen-ht https://github.com/solid-design-system/figma/issues/88 Are the tokens already updated in Figma for the `sd-accordion`?
When I read it correctly, it's updated for the button, but not for the `sd-accordion`. This currently blocks updating the tokens.
=> feat: ✨ update tokens

packages/tokens/src/create-theme.cjs
=> fix: implement correct boxShadows

packages/components/src/solid-styles.css, packages/components/src/styles/interactive/interactive.css, packages/components/src/styles/interactive/interactive.declaration.ts, packages/components/src/styles/interactive/interactive.stories.ts
This PR introduces a new style which is a low-level utility for interactive elements without padding.
=> feat: sd-interactive

.github/ISSUE_TEMPLATE/ci-issue-template.md, .github/ISSUE_TEMPLATE/feature-issue-template.md, .github/ISSUE_TEMPLATE/new-component-issue-template.md
- added User Story section to the template for chore-, ci- and feature-issues
- added new template fpr new component issues
- closes #369
=> docs: add user story to templates and create new comp template

.github/ISSUE_TEMPLATE/new-component-issue-template.md
Change name in new component issue template to avoid error.
=> docs: 📚 Change name for new component issue

packages/components/src/styles/interactive/interactive.css, packages/components/src/styles/interactive/interactive.stories.ts
Moved changes to sd-interactive into a separate PR. This PR along with the sd-carousel PR #324 will close  issue #239
=> feat: ✨ add inverted styles to sd-interactive

packages/components/.storybook/preview.js, packages/components/src/components/drawer/drawer.stories.ts, packages/components/src/components/dropdown/dropdown.stories.ts, packages/components/src/styles/interactive/interactive.stories.ts, packages/components/tailwind.config.cjs
=> docs: 📚 make tailwind classes available in stroybook

packages/components/src/internal/register-custom-element.ts
Per accident I commited directly to main, which was raising linting bugs. This fix removes that.
=> chore: fix linting errors on main

packages/components/src/docs/General/1-Introduction.mdx
=> docs: 📚 clarify usage of Pattern vs. Sample & Style vs. Component

packages/components/src/components/icon/icon.stories.ts, packages/components/src/components/icon/icon.test.ts
1. I updated the docs for `sd-icon`.
2. I fixed the tests using the documented approach.
=> fix: 🐛 provide docs how to use registerIconLibrary with UMD bundle

.github/workflows/lint-pr.yml
added a linter for PR titles to make sure they are valid and aligned with Semantic Release. Closes #60 
=> ci: 👷 add PR title check workflow

packages/components/.storybook/solid-theme.ts
Changes secondary color in Storybook to our primary blue. Closes #415 
=> docs: 📚 adjust Storybook colors to meet AA criteria

packages/components/src/components/accordion/accordion.stories.ts, packages/components/src/components/accordion/accordion.ts
The requirement: https://github.com/solid-design-system/solid/issues/450
=> fix: 🤔 added part selector to accordion content slot.

renovate.json
Update auto-merge and schedule configurations. Closes #473.
=> ci: 👷 improve/automate renovate

packages/components/CHANGELOG.md, packages/components/package.json, packages/components/prepare-changelog.sh, pnpm-lock.yaml
Setup script to copy components of our default Changelog from Storybook into the components package root folder. This makes it easier for tools like Renovate to parse through it. Closes #414. 
=> docs: 📚 improve changelog

.eslintrc.cjs, .github/workflows/check-pr.yml, package.json, packages/components/.storybook/preview-head.html, packages/components/package.json, packages/components/scripts/storybook/helper.ts, packages/components/src/components/accordion-group/accordion-group.test.ts, packages/components/src/components/button/button.ts, packages/components/src/components/drawer/drawer.test.ts, packages/components/src/docs/General/2-Prerequisites.mdx, packages/components/src/internal/form.ts, packages/components/src/patterns/quote/quote.stories.ts, packages/components/src/styles/interactive/interactive.stories.ts, packages/placeholders/package.json, packages/tokens/package.json, pnpm-lock.yaml
Renovate unfortunately added stuff witch wasn't caught by our quality gate. This PR fixes some broken stuff.
=> chore: improve verify and fix broken repo

package.json, pnpm-lock.yaml, renovate.json
This reverts commit 4f6fd131dc1a9be9fce0196e30f45fa2543e4eec.
=> chore: 🔧 Revert "chore(deps): lock file maintenance (#506)"

packages/components/scripts/node-version-components.cjs
=> chore: remove versioned web type generation

packages/components/src/components/icon/icon.stories.ts
Replaces sl-icon with sd-icon in docs. Closes #486
=> fix: 🤔 Typo -> sl-icon

packages/components/src/components/radio-group/radio-group.ts, packages/components/src/components/radio/radio.ts
Remove BEM
fix margin on items in horizontal radio-group
=> refactor: sd-radio & sd-radio-group

packages/components/src/components/input/input.ts
correct version from 1.0 to 1.24.0
=> docs: update sd-input component version

packages/components/.storybook/addons/theme-generator/colorCalculations.ts, packages/components/.storybook/preview.js, packages/components/src/components/header/header.stories.ts
No time for descriptions. We have to fix Storybook.
=> docs: fix storybook

packages/tokens/src/create-theme.cjs
Added z-index tokens for tailwind. Availability as CSS variables is still a WIP .Closes #521
=> fix: 🤔 add z-index tokens 

renovate.json
set rebaseWhen to never. Closes #581 
=> ci: 👷 prevent renovate trigger checks multiple times

packages/components/src/docs/Migration/ui-headline.mdx
Added migration guide for sd-headline. Closes #605.
=> docs: 📚 add migration guide for sd-headline

packages/components/src/docs/Migration/ui-leadtext.mdx
=> docs: 📚 add migration guide for sd-leadtext 

packages/components/src/docs/Migration/ui-quotation.mdx
=> docs: 📚 add migration guide for sd-quote

packages/components/src/docs/Migration/ui-video.mdx
Added migration guide for sd-video. Closes #602.
=> docs: 📚 add migration guide for sd-video

packages/components/src/styles/headline/headline.stories.ts
Refactored headline stories to show h4 tag instead of p and div.
Closes #599 
=> docs: 📚 improve a11y on headline examples

packages/components/src/components/accordion/accordion.stories.ts, packages/components/src/components/accordion/accordion.ts
=> fix: 🤔 add missing part for accordion-border

packages/components/.storybook/preview.js
Updated preview.js so that when opening the "show code" dropdown in the "Default" story of a component, a cleaned up code version of the story is displayed.
Closes #661 
=> docs: 🤔 storybook code-view cleaned up

.github/workflows/check-pr.yml, .github/workflows/chromatic-main.yml
=> chore: prevent Chromatic on PRs with [skip chromatic]

packages/components/scripts/storybook/helper.ts, packages/components/src/components/button/button.ts
=> docs: 📚 remove @state decorators and add non-private methods to Storybook

packages/components/src/components/teaser/teaser.stories.ts, packages/components/src/components/teaser/teaser.ts
=> feat: ✨ add interactive teaser sample

packages/components/src/docs/General/03-Installation.mdx
Add the Stencil/Webpack import path documentation in addition to current documentation.
Closes #323 
=> docs: 📚 npm package import stencil / webpack

packages/components/src/components/select/select.ts
Added a z-index on ::part(popup) in sd-select. 
Closes #534 
=> fix: 🤔 z-index in sd-select

packages/components/src/solid-styles.css, packages/components/src/styles/list/list.css, packages/components/src/styles/list/list.declaration.ts, packages/components/src/styles/list/list.stories.ts
=> feat: ✨ add sd-list (CSS style)

packages/components/scripts/node-version-components.cjs
Closes #527 . I deleted the components/dist folder on my local setup and ran 'pnpm build.npm'. That seemed to resolve all the errors I received. After that, I added the same lines of code removed by #526. This seems to be working fine for now. 
=> fix: 🤔 re-integrate web-types generation [skip chromatic]

README.md, packages/tokens/README.md
Adding tokens handling for maintainers in Figma to README
closes #531 
=> docs: add tokens handling [skip chromatic]

.github/workflows/chromatic-main.yml
Changed chromatic action version to latest.
=> chore: use latest chromaui/action version

.github/workflows/check-pr.yml
I updated the instance of chromatic actions in check-pr.yml in addition to the already updated one in chromatic-main.yml #716
=> ci: update chromatic actions in pr-check

LICENSE.md, packages/components/README.md, packages/placeholders/LICENSE.md, packages/placeholders/README.md, packages/theming/LICENSE.md, packages/theming/README.md, packages/tokens/LICENSE.md, packages/tokens/README.md
adding a license file to each single package in the repo and link in the main license file from the monorepo.
closes #721
=> docs: add license files to each package [skip chromatic]

packages/components/src/Legal/Imprint.mdx
adding an imprint page to storybooks legal chapter
closes #712
=> docs: add imprint file to storybooks legal chapter [skip chromatic]

DEVELOPER_STARTING_GUIDE.md, packages/components/src/_components/avatar/avatar.ts, packages/components/src/_components/color-picker/color-picker.ts, packages/components/src/_components/icon-button/icon-button.ts, packages/components/src/_components/range/range.ts, packages/components/src/_components/rating/rating.ts, packages/components/src/_components/relative-time/relative-time.ts, packages/components/src/_components/tab-group/tab-group.ts, packages/components/src/components/brandshape/brandshape.ts, packages/components/src/components/button/button.ts, packages/components/src/components/carousel/carousel.ts, packages/components/src/components/checkbox/checkbox.ts, packages/components/src/components/icon/icon.ts, packages/components/src/components/input/input.ts, packages/components/src/components/option/option.ts, packages/components/src/components/radio-group/radio-group.ts, packages/components/src/components/radio/radio.ts, packages/components/src/components/select/select.ts, packages/components/src/components/switch/switch.ts, packages/components/src/components/teaser/teaser.ts, packages/components/src/components/textarea/textarea.ts
=> docs: 📚 clean up @state decorators and non-private methods in storybook

packages/components/src/styles/table-cell/table-cell.css, packages/components/src/styles/table-cell/table-cell.declaration.ts, packages/components/src/styles/table-cell/table-cell.stories.ts, packages/components/src/styles/table/table.css
=> feat: ✨add shadow variant for sd-table-cell 

packages/tokens/src/tokens.json
*Add opacity tokens 55, 60, 80*
=> feat: Add opacity tokens

packages/components/src/styles/headline/headline.css
=> fix: 🤔 sd-headline does not include a line-height style

packages/components/src/styles/table-cell/table-cell.stories.ts
Add sortable table sample in sd-table-cell.
Closes #380 
=> docs: 📚  sd-table-cell add sortable sample

packages/tokens/README.md
adding additional info for tokens Readme
=> docs: add additional info for tokens Readme [skip chromatic]

packages/components/src/styles/table-cell/table-cell.stories.ts, packages/components/src/utilities/localize.ts
=> fix: add german language to bundle

.eslintrc.cjs, packages/components/src/components/navigation-item/navigation-item.ts
[Context](https://teams.microsoft.com/l/message/19:sycqZKo6K_-P5eYh0H4Xn2UpoKmti8Ar5SICMb9z7C41@thread.tacv2/1707906984350?tenantId=2eb07b91-f9f8-437b-a89e-59f55e565c11&groupId=cec93f98-ceee-42bd-bfde-a6b51fc1194e&parentMessageId=1707906984350&teamName=Solid%20Design%20System%20Community%20(Team)&channelName=General&createdTime=1707906984350)
=> fix: fix wrong customElement import + update eslint rule

CONTRIBUTING.md
adding a pre-refinement section to contribution guide.
closes #616
=> docs: add pre-refinement info to contribution guide [skip chromatic]

packages/components/src/components/input/input.ts, packages/components/src/components/select/select.stories.ts, packages/components/src/components/select/select.ts
=> fix: 🤔 min-width of input element does not match responsiveness of sd-select/sd-input 

.eslintignore, SECURITY.md, packages/placeholders/README.md, packages/placeholders/package-lock.json, packages/placeholders/package.json, packages/placeholders/src/solid-faker.js, packages/placeholders/tsconfig.json, packages/placeholders/types/solid-faker.d.ts, pnpm-lock.yaml
closes #392 
Adds a utility class SolidFaker with a singleton instance solidFaker which can be imported the same way as Faker JS:
import { faker } from '@faker-js/faker/locale/de';
import { solidFaker } from '@solid-design-system/placeholders';
At least, that is my goal.  I have written this in pure JS as I observed was done in the "theming" package to avoid complexity with TypeScript and a build process.
The file solid-faker.js is about 4kb (3.866 bytes) without minification which sounds reasonable compared to the 1.5mb that the Faker JS package was using.  The goal of this ticket was to immediately solve a ticket for the CMS repo:
https://jira.apps.union-investment.de/browse/PB2B-6559 while providing the utility through a package for distributed use in the future.
Is this a sufficient …
=> feat: ✨ extend placeholder package with placeholder texts

SECURITY.md, packages/components/src/components/video/video.test.ts
Closes #483. 
I followed the same format with the comments as already exists in `dropdown.test.ts`.
=> fix: 🤔 sd-video accessibility test [skip chromatic]

packages/components/src/components/teaser/teaser.stories.ts
=> docs: add more samples to sd-teaser

packages/components/src/components/notification/notification.stories.ts
Added hint to look at the **Show code** option. Closes #718.
=> docs: 📚 improve sd-notification docs

README.md
Added hints for helpful commands: 
- pnpm test.watch
- pnpm test.component [component-name]
Closes #413.
=> docs: 📚 Add more helpful commands to CONTRIBUTING.md 

SECURITY.md, packages/components/src/solid-styles.css, packages/components/src/styles/copyright/copyright.css, packages/components/src/styles/copyright/copyright.declaration.ts, packages/components/src/styles/copyright/copyright.stories.ts, packages/components/src/styles/media/media.css, packages/components/src/styles/media/media.declaration.ts, packages/components/src/styles/media/media.stories.ts
=> feat: ✨ add sd-media + sd-copyright - CSS style

packages/components/src/components/header/header.stories.ts
Replaced FinanzAgenda logo with a more generic partner logo in sd-header samples.
Closes #760 
=> docs: replace FinanzAgenda logo with partner logo

packages/placeholders/README.md, packages/placeholders/package.json
=> feat: add placeholder video

pnpm-lock.yaml
This reverts commit d50dc95e4d1d40d308b8dbf9f32ebac6f5cb2458.
=> chore: revert update dependency @mariohamann/wc-storybook-helpers

packages/components/src/styles/container/container.css, packages/components/src/styles/container/container.declaration.ts
convert all tailwind arbitrary values to plain css in container style
=> fix: arbitrary values in container style

packages/components/src/components/button/button.ts
Changed cta variant of sd-button to accent-500. Closes #809.
=> fix: 🤔 CTA button color 

packages/components/src/docs/Migration/ui-container.mdx
Added a migration guide from ui-container to sd-container and sd-brandshape. 
Closes #789 
=> docs: 📚 add migration guide from ui-container to sd-container and sd-brandshape [skip chromatic] 

packages/components/src/components/navigation-item/navigation-item.ts
=> fix: adjust vertical spacing of navigation-item#vertical

packages/components/src/docs/General/07-Tokens.mdx
Closes [#841](https://github.com/solid-design-system/solid/issues/841)
=> docs: 📚 font-size tokens not represented in samples

packages/components/src/docs/General/07-Tokens.mdx
Add explanation on difference between "UI Core" and "UI semantics" Tokens.
Note: Needs to be changed in Figma as well.
Closes #745 
=> docs: 📚 add explanation on token groups [skip chromatic]

package.json, packages/components/package.json, packages/components/web-test-runner.config.js, patches/tailwindcss@3.4.1.patch, pnpm-lock.yaml
This is a very urgent fix. Currently we provide font defaults in our components which are not correct. This is done by overriding the original https://tailwindcss.com/docs/preflight file.
In addition this PR fixes husky not working properly.
=> fix: remove wrong font stack from components

packages/components/.storybook/preview.js, packages/components/package.json, packages/components/scripts/storybook/helper.ts, pnpm-lock.yaml
See screenshot:
- remove package for formatting
- use prettier for formatting
- add Table of Contents
=> docs: optimize code output + add TOCs

packages/components/package.json, packages/placeholders/package-lock.json, packages/placeholders/package.json, packages/theming/package.json, pnpm-lock.yaml
Reverts solid-design-system/solid#888. This PR was merged while some tests were still failing.
=> chore(deps): Revert update dependency typescript to v5.4.3

packages/components/src/docs/Migration/ui-image.mdx
=> docs: 📚 add migration guide from ui-image to sd-media and sd-copyright [skip chromatic]

packages/components/src/styles/copyright/copyright.css
The PR was created during a working session with @christophsaile and Niklas. We expected that this could solve something – but could solve it another way. Still, the changes are an improvement, therefore they're fine.
---
=> fix: 🐛 remove TailwindCSS var from sd-copyright

packages/components/src/styles/footnote/footnote.css, packages/components/src/styles/footnote/footnote.declaration.ts, packages/components/src/styles/footnote/footnote.stories.ts
https://github.com/solid-design-system/solid/issues/925
=> fix: 🐛  add inverted color to sd-footnote

.github/pull_request_template.md
- adding markdown comments to template
- adding [skip chromatic] flag as default to PR-title in the template
=> chore: improve pr template [skip chromatic]

packages/components/src/styles/paragraph/paragraph.stories.ts
https://github.com/solid-design-system/solid/issues/910
=> fix: 🤔 change HTML tag from div to p

packages/components/src/components/button/button.ts
=> fix: 🤔 sd-button border-radius

packages/components/src/docs/General/07-Tokens.mdx
=> docs: 🤔 images in ratio-tokens not displayed correctly

packages/components/src/styles/list/list.css
=> fix: 🤔 align horizontal list

packages/components/src/components/select/select.ts
=> fix: 🤔 sd-select - correct styling

packages/components/src/patterns/supernumber/supernumber.stories.ts
=> docs: fix supernumber countup.js

CONTRIBUTING.md
adding a section about issue estimation and velocity tracking to the developer starting guide.
closes #928
=> docs: add new estimation (story points) section to developer guide [skip chromatic]

packages/components/src/components/map-marker/map-marker.stories.ts, packages/components/src/components/map-marker/map-marker.ts, packages/components/src/docs/Migration/ui-map-marker.mdx, packages/components/tailwind.config.cjs, packages/tokens/src/create-theme.cjs
=> feat: ✨ add sd-map-marker

packages/components/src/docs/General/03-Installation.mdx
closes #984 by updating docs. Everything was tested in our demo and in @Fl0rianFischer's repo.
=> docs: fix documentation for styles (closes #984)

packages/components/src/patterns/quote/quote.stories.ts, packages/components/src/patterns/supernumber/supernumber.stories.ts
Improved supernumber pattern documentation and removed "component" terminology in all patterns that included it. Closes #961.
=> docs: 📚 supernumber pattern - add information/guidance

packages/components/.storybook/main.cjs, packages/components/src/components/teaser-media/teaser-media.stories.ts, packages/components/src/components/teaser/teaser.stories.ts, packages/components/src/components/video/video.stories.ts, packages/components/src/docs/General/07-Tokens.mdx, packages/components/src/patterns/quote/quote.stories.ts, packages/components/src/styles/copyright/copyright.stories.ts, packages/components/src/styles/flag/flag.stories.ts, packages/components/src/styles/media/media.stories.ts, packages/placeholders/README.md
=> feat: ✨add placeholder video

.github/workflows/check-pr.yml, DEVELOPER_STARTING_GUIDE.md, renovate.json
- removes all automatic updates from renovate config unless its a security update and add custom PR title prefix
- adds branch exception to chromatic workflow to ignore security updates from renovate
- adds a new chapter to the developer guide to explain the new procedure
closes #914
=> ci: update renovate process [skip chromatic]

packages/components/src/styles/table-cell/table-cell.stories.ts
Removed placeholder for fixed column in sd-table-cell sample: https://github.com/solid-design-system/solid/issues/1044
=> fix: 🤔 remove placeholder for fixed column sample

renovate.json
=> ci: 👷 Ensure Renovate PRs are Exclusively Security Related

renovate.json
=> ci: 👷 Remove Security Label from general PRs

pnpm-lock.yaml
Updating our dependencies to clear the dependency dashboard. Related to #460. 
All tests are passing locally.
=> ci: update all dependencies

.github/workflows/check-pr.yml
Updated the workflow to depend on formatting, rather than e2e tests. #1161
=> ci: 👷 Remove chromatic's dependency on unit tests

packages/components/src/components/icon/library.default.ts
Fixes https://github.com/solid-design-system/solid/issues/1125
=> fix: fix accent default color in icons

packages/tokens/src/tokens.json
following #1017 
token *background-transparent.primary.20 is added
=> ci(tokens): adding transparent primary.20 [skip chromatic]

packages/components/src/components/navigation-item/navigation-item.stories.ts, packages/components/src/components/navigation-item/navigation-item.ts
=> fix: fix jumping text in navigation item

README.md
Adding conventional-commits badge to README
=> docs(README): Adding conventional-commits badge to README [skip chromatic]

README.md
Link to code of conduct is broken, this fixes it
=> docs(README): Correct link to code of conduct [skip chromatic]

packages/components/src/components/brandshape/brandshape.stories.ts, packages/components/src/components/brandshape/brandshape.ts, packages/components/src/docs/Migration/ui-container.mdx
Added border and image variants to the sd-brandshape component.
Closes #1004
=> feat: ✨ implement new brandshape variants

.github/ISSUE_TEMPLATE/simple-design-feature-issue-template.md, .github/ISSUE_TEMPLATE/simple-dev-feature-template.md
adds 2 new issue templates to the project:
- simple dev issue for features which are not an epic
- simple design issue for features which are not an epic
=> ci: add new issue templates for simple dev and design features (no-epic) [skip chromatic]

packages/placeholders/src/solid-faker.js
This fix should ensure that repeated calls with the same seed produce consistent outputs.
=> fix: solid faker seed

packages/placeholders/README.md, packages/placeholders/package.json, packages/placeholders/src/solid-faker.js, packages/placeholders/src/solid-faker.test.js
=> fix: solid faker seed for paragraphs and sentences

packages/components/src/styles/container/container.css
=> fix: missing border sd-container variant-border-neutral-400

packages/components/src/components/badge/badge.stories.ts, packages/components/src/components/badge/badge.test.stories.ts, packages/components/src/components/badge/badge.ts
=> feat: sd-badge docs [skip chromatic]

packages/components/src/components/tag/tag.stories.ts, packages/components/src/components/tag/tag.test.stories.ts, packages/components/src/templates/tags.stories.ts
=> docs: sd-tag docs [skip chromatic]

packages/components/src/components/button/button.stories.ts
=> docs: sd-button docs update [skip chromatic]

packages/components/src/components/link/link.stories.ts, packages/components/src/components/link/link.test.stories.ts, packages/components/src/components/link/link.ts, packages/components/src/templates/link-list.stories.ts
=> docs: sd-link docs [skip chromatic]

packages/components/src/components/accordion/accordion.stories.ts, packages/components/src/components/accordion/accordion.test.stories.ts
=> docs: sd accordion docs [skip chromatic]

packages/components/src/components/accordion/accordion.ts, packages/components/src/components/quickfact/quickfact.stories.ts, packages/components/src/components/quickfact/quickfact.test.ts, packages/components/src/components/quickfact/quickfact.ts, packages/components/src/docs/Migration/ui-quickfact-group.mdx, packages/components/src/docs/Migration/ui-quickfact.mdx
Closes #1015
This is an alterantive approach to create the quickfact by extending the accordion and giving the accordion a new feature to get an icon.
=> feat: add quickfact

packages/components/src/components/carousel-item/carousel-item.stories.ts, packages/components/src/components/carousel-item/carousel-item.test.stories.ts
=> docs: sd-carousel-item docs [skip chromatic] 

packages/components/src/components/accordion-group/accordion-group.stories.ts, packages/components/src/templates/accordion-group.stories.ts
=> docs: sd-accordion-group docs update [skip chromatic]

packages/components/scripts/vite-plugin-fetch-icons-from-cdn.ts, packages/components/src/components/icon/library.default.ts
=> feat: update celum icons url

packages/components/src/components/divider/divider.stories.ts, packages/components/src/components/divider/divider.test.stories.ts
The test.stories file was created. Re-wrote documentation for the sd-divider component.
=> docs: sd-divider docs [skip chromatic]

packages/components/src/components/carousel/carousel.stories.ts, packages/components/src/components/carousel/carousel.test.ts, packages/components/src/components/carousel/carousel.ts
Closes  #1191. Updating scrolling logic to ensure that the page number calculation is accurate no matter the divisibility of slides-per-page and slides-per-move.
=> fix: 🤔 sd-carousel - numbered variant - show total clicks

packages/components/src/docs/Migration/ui-richtext.mdx
Added Migration Guide. Closes  #1115
=> docs: 📚 add migration guide for sd-prose/ui-richtext

packages/components/src/components/divider/divider.stories.ts
=> docs: sd-divider make default interactive

packages/components/src/docs/Migration/Intro.mdx, packages/components/src/docs/Migration/ui-qrcode.mdx
=> docs: sd-qr-code – add documentation

packages/components/src/solid-styles.css, packages/components/src/styles/hidden-links/hidden-links.css, packages/components/src/styles/hidden-links/hidden-links.declaration.ts, packages/components/src/styles/hidden-links/hidden-links.stories.ts
=> feat: ✨ add style sd-hidden-links

packages/components/.storybook/preview.js, packages/components/src/components/icon/icon.stories.ts, packages/components/src/components/icon/library.default.ts
=> feat: use new default green for ui icons

packages/components/src/styles/chip/chip.stories.ts, packages/components/src/styles/flag/flag.declaration.ts, packages/components/src/styles/flag/flag.stories.ts, packages/components/src/styles/flag/flag.test.stories.ts, packages/components/src/templates/flag.stories.ts
=> docs: sd-flag docs [skip chromatic]

packages/components/src/components/spinner/spinner.stories.ts, packages/components/src/components/spinner/spinner.test.stories.ts
=> docs: sd-spinner docs [skip chromatic] 

packages/components/src/docs/Migration/ui-surrounding-map.mdx
=> docs: 📚 deprecate ui-surrounding-map [skip chromatic]

packages/components/src/docs/Migration/Intro.mdx
=> docs: 📚 Add documentation to all discontinued ui-components from CL 

packages/components/src/styles/leadtext/leadtext.css, packages/components/src/styles/prose/prose.stories.ts
=> feat: ✨ make sd-prose work better with sd-leadtext

packages/components/src/components/carousel/carousel.stories.ts, packages/components/src/components/carousel/carousel.test.stories.ts, packages/components/src/templates/carousel-with-images.stories.ts
=> docs: sd-carousel docs [skip chromatic]

packages/components/.storybook/main.ts, packages/components/.storybook/preview.js, packages/components/scripts/storybook/docs-codepen-enhancer.ts, packages/components/scripts/storybook/env-package-versions.ts
=> docs: add codepen button

packages/components/src/components/dialog/dialog.ts, packages/components/src/components/drawer/drawer.ts, packages/components/src/components/notification/notification.ts
=> fix: add missing labels for close buttons

packages/components/src/components/radio-button/radio-button.ts
=> fix: 🤔 add missing neutral-500 border on disabled+checked sd-radio-buttons

packages/components/src/styles/footnotes/footnotes.css, packages/components/src/styles/footnotes/footnotes.stories.ts
=> fix: incorrect indent of sd-footnotes 

packages/components/src/components/brandshape/brandshape.stories.ts, packages/components/src/components/brandshape/brandshape.test.stories.ts, packages/components/src/templates/brandshape-template.stories.ts, packages/components/src/templates/brandshape.stories.ts
=> docs: sd-brandshape docs [skip chromatic]

packages/components/src/styles/copyright/copyright.stories.ts, packages/components/src/styles/copyright/copyright.test.stories.ts
=> docs: sd-copyright docs [skip chromatic]

packages/components/src/components/switch/switch.stories.ts, packages/components/src/components/switch/switch.test.stories.ts
=> docs: sd-switch docs [skip chromatic]

packages/components/src/components/checkbox/checkbox.stories.ts, packages/components/src/components/checkbox/checkbox.test.stories.ts
=> docs: sd-checkbox docs [skip chromatic] 

packages/components/src/components/radio-button/radio-button.stories.ts, packages/components/src/components/radio-button/radio-button.test.stories.ts, packages/components/src/components/radio-button/radio-button.ts, packages/components/src/templates/radio-button-group.stories.ts
=> docs: sd-radio-button docs [skip chromatic] 

packages/components/src/components/scrollable/scrollable.stories.ts, packages/components/src/components/scrollable/scrollable.test.stories.ts, packages/components/src/components/scrollable/scrollable.ts
=> docs: sd-scrollable docs [skip chromatic]

packages/components/src/components/step-group/step-group.stories.ts, packages/components/src/components/step-group/step-group.test.stories.ts, packages/components/src/components/step-group/step-group.ts, packages/components/src/templates/step-group.stories.ts
=> docs: sd-step-group docs [skip chromatic] 

packages/components/src/components/tab-group/tab-group.stories.ts, packages/components/src/components/tab-group/tab-group.test.stories.ts, packages/components/src/components/tab-panel/tab-panel.stories.ts, packages/components/src/components/tab-panel/tab-panel.test.stories.ts, packages/components/src/components/tab/tab.stories.ts, packages/components/src/components/tab/tab.test.stories.ts, packages/components/src/components/tab/tab.ts, packages/components/src/templates/tabs.stories.ts
This PR contains the rewrite for the following components:
- sd-tab
- sd-tab-panel
- sd-tab-group
=> docs: sd-tab docs [skip chromatic] 

packages/components/src/components/option/option.stories.ts, packages/components/src/components/option/option.test.stories.ts
=> docs: sd-option docs [skip chromatic]

packages/components/src/styles/leadtext/leadtext.stories.ts, packages/components/src/styles/leadtext/leadtext.test.stories.ts
=> docs: sd-leadtext docs [skip chromatic]

packages/components/.storybook/preview-head.html
=> feat: hide default storie for styles components [skip chromatic]

packages/components/src/styles/mark/mark.stories.ts, packages/components/src/styles/mark/mark.test.stories.ts
=> docs: sd-mark docs [skip chromatic]

packages/components/src/styles/footnotes/footnotes.stories.ts, packages/components/src/styles/footnotes/footnotes.test.stories.ts, packages/components/src/templates/footnotes-set-start.stories.ts
=> docs: sd-footnotes docs [skip chromatic]

packages/components/src/styles/meta/meta.stories.ts, packages/components/src/styles/meta/meta.test.stories.ts
=> docs: sd-meta docs [skip chromatic]

packages/components/src/components/video/video.stories.ts, packages/components/src/components/video/video.test.stories.ts, packages/components/src/templates/video-with-description-and-copyright.stories.ts
=> docs: sd-video docs [skip chromatic]

packages/components/src/styles/paragraph/paragraph.stories.ts, packages/components/src/styles/paragraph/paragraph.test.stories.ts
=> docs: sd-paragraph docs [skip chromatic]

packages/components/src/docs/General/08-Tokens.mdx
=> docs: 📚 Remove unused variable in Tokens.mdx docs 

packages/components/src/components/quickfact/quickfact.stories.ts, packages/components/src/components/quickfact/quickfact.test.stories.ts, packages/components/src/templates/quickfact-grouping.stories.ts, packages/components/src/templates/quickfact.stories.ts
=> docs: sd quickfact docs [skip chromatic]

packages/components/src/styles/interactive/interactive.stories.ts, packages/components/src/styles/interactive/interactive.test.stories.ts, packages/components/src/templates/interactive.stories.ts
=> docs: sd-interactive docs [skip chromatic]

packages/components/src/styles/display/display.stories.ts, packages/components/src/styles/display/display.test.stories.ts
=> docs: sd-display docs [skip chromatic]

packages/components/src/styles/table/table.stories.ts, packages/components/src/styles/table/table.test.stories.ts
=> docs: sd-table-docs [skip chromatic]

packages/components/src/styles/hidden-links/hidden-links.stories.ts, packages/components/src/styles/hidden-links/hidden-links.test.stories.ts
=> docs: sd-hidden-links docs [skip chromatic]

packages/components/src/components/checkbox-group/checkbox-group.stories.ts, packages/components/src/components/radio-group/radio-group.stories.ts, packages/components/src/components/textarea/textarea.stories.ts, packages/components/src/components/tooltip/tooltip.stories.ts, packages/components/src/styles/container/container.stories.ts, packages/components/src/styles/footnotes/footnotes.stories.ts, packages/components/src/styles/leadtext/leadtext.stories.ts, packages/components/src/styles/mark/mark.stories.ts, packages/components/src/styles/meta/meta.stories.ts, packages/components/src/styles/paragraph/paragraph.stories.ts, packages/components/src/templates/footnotes.stories.ts
=> docs: small fixes [skip chromatic]

packages/components/src/styles/table-cell/table-cell.stories.ts, packages/components/src/styles/table-cell/table-cell.test.stories.ts, packages/components/src/templates/table-cell.stories.ts, packages/components/src/templates/table.stories.ts
Updated documentation and moved sample to template #1221
=> docs: sd-table-cell [skip chromatic]

packages/components/src/components/checkbox/checkbox.ts, packages/components/src/components/radio/radio.ts, packages/components/src/components/switch/switch.ts
Reduce clickable area to component + label. #909
=> fix: 🤔 reduce clickable area to label length in sd-switch, sd-radio and sd-checkbox 

.github/pull_request_template.md
added a comment to the PR template in order to give more guidance on how and where to add tests.
=> ci: add test comment to PR template [skip chromatic]

packages/components/src/styles/footnotes/footnotes.css
Changed inverted footnote color to primary-400. Closes  #1353.
=> fix: 🤔 sd-footnotes inverted variant color

packages/components/src/components/link/link.ts, packages/components/src/styles/hidden-links/hidden-links.declaration.ts, packages/components/src/styles/list/list.declaration.ts
Closes #1209.
I did not change the "since" version number as we did not make any changes in the component. Please let me know if I should change it to our current version.
=> fix: 🤔 update experimental status

packages/components/src/components/map-marker/map-marker.ts
Closes #979. Added a white circle inside our existing map marker (main variant).
=> fix: 🤔 map-marker main -> white circle

packages/components/.storybook/preview.js, packages/components/src/components/icon/icon.stories.ts, packages/components/src/components/icon/icon.test.stories.ts
I rewrote the docs to make them work better with our other docs.
=> docs: 📚 improve icon docs

packages/components/src/templates/tag.stories.ts
Closes https://github.com/solid-design-system/solid/issues/1447
=> docs: update tag template docs [skip chromatic]

packages/components/src/templates/supernumber.stories.ts
Closes https://github.com/solid-design-system/solid/issues/1451.
=> docs: update supernumber template [skip chromatic]

packages/components/src/templates/link.stories.ts
Closes https://github.com/solid-design-system/solid/issues/1445
=> docs: update link template docs [skip chromatic]

packages/components/src/components/button/button.stories.ts, packages/components/src/templates/button.stories.ts
Closes https://github.com/solid-design-system/solid/issues/1434.
=> docs: create button template [skip chromatic]

.github/ISSUE_TEMPLATE/new-component-issue-template.md, .github/ISSUE_TEMPLATE/new-style-component-issue-template.md, DEVELOPER_STARTING_GUIDE.md, packages/components/src/docs/General/01-Introduction.mdx, packages/components/src/docs/General/11-FAQ.mdx
Closes #1116. Moved @miguelxnxn changes to a branch.
=> docs: improve FAQ 

packages/components/src/templates/table.stories.ts
Closes #749. Confirmed that this table is moved to templates and is no longer included in screenshots. Hence, I only removed the data-chromatic attribute with no additional changes :)
=> docs: 📚 replace randomized numbers in sortable table sample 

packages/components/src/components/navigation-item/navigation-item.stories.ts, packages/components/src/templates/badge.stories.ts
Closes https://github.com/solid-design-system/solid/issues/1443
=> docs: update badge template docs [skip chromatic]

packages/theming/src/color-calculation.js
improve regex
closes #785
closes #1564
=> fix: improve regex [skip chromatic]

packages/components/src/components/checkbox-group/checkbox-group.stories.ts, packages/components/src/components/checkbox-group/checkbox-group.ts, packages/components/src/components/checkbox/checkbox.stories.ts, packages/components/src/components/checkbox/checkbox.ts, packages/components/src/components/radio-button/radio-button.stories.ts, packages/components/src/components/radio-group/radio-group.stories.ts, packages/components/src/components/radio-group/radio-group.ts, packages/components/src/components/radio/radio.stories.ts, packages/components/src/components/radio/radio.ts
=> feat: add 'md' size to sd-radio, sd-checkbox and sd-checkbox-group

.github/workflows/upload-storybook-to-github-pages.yml
This automatically creates and updates a comment in the respective PR with a link to the Storybook deployment on GitHub pages to significantly increase the speed of reviewing for unscreenshotted PRs.
=> chore: add comment with link to PR [skip chromatic]

packages/components/scripts/node-optimize-chromatic.cjs, packages/components/src/components/checkbox/checkbox.test.stories.ts, packages/components/src/components/input/input.test.stories.ts, packages/components/src/components/select/select.test.stories.ts, packages/components/src/components/textarea/textarea.test.stories.ts
This fixes the issue of false diffs because of running spinners (delay had to be bigger beacuse of bigger stories) and freshly captured stories that showed a new time every time.
I re-tested by commiting another commit and everything seems to work.
Ticket: https://github.com/solid-design-system/solid/issues/1394
=> chore: fix false diffs on Chromatic (close #1394)

packages/components/src/templates/quickfact.stories.ts
Closes https://github.com/solid-design-system/solid/issues/1449.
=> docs: update quickfact template [skip chromatic]

packages/components/src/components/brandshape/brandshape.stories.ts, packages/components/src/components/brandshape/brandshape.ts
Closes [#1468](https://github.com/solid-design-system/solid/issues/1468)
=> fix: sd-brandshape a11y

packages/components/src/components/audio/audio.stories.ts
This PR updates includes the transcript in all stories as per design request.
=> chore: include transcript in all stories

.github/ISSUE_TEMPLATE/fix-issue-template.md, .github/ISSUE_TEMPLATE/performance-issue-template.md
- adds comment on how to add reproduction details into our performance and bugfix issue templates
closes #1561
=> chore: add reproduction comment into fix and performance issue template [skip chromatic]

packages/components/src/templates/tag.stories.ts
=> docs: add accessible label to tag stories

packages/components/src/components/radio-button/radio-button.stories.ts
=> docs: sd-radio-button a11y

packages/docs/src/stories/packages/docs/02-Changelog.mdx
=> fix: add correct path to changelog of docs

packages/docs/src/stories/styles/mark.stories.ts, packages/docs/src/stories/styles/mark.test.stories.ts, packages/docs/src/stories/templates/mark.stories.ts
Closes #1613, #1532 
Colors won't be changed since it is already aligned with the brand, therefore there are only documentation updates
=> docs: update sd-mark templates

packages/components/src/components/select/select.ts
Added the class placeholder-neutral-700 class to the input element to style the placeholder. Closes #1616
=> fix: set sd-select placeholder text-color to neutral-700

.changeset/green-beers-promise.md
=> chore: 🔧 fix deployment

.changeset/grumpy-avocados-drum.md, packages/components/src/components/checkbox/checkbox.test.ts, packages/components/src/components/checkbox/checkbox.ts
Closes [1472](https://github.com/solid-design-system/solid/issues/1472)
=> fix: sd-checkbox accessible validation state

.changeset/slimy-paws-admire.md, packages/components/src/components/select/select.test.ts, packages/components/src/components/select/select.ts, packages/components/src/internal/default-value.ts, packages/components/src/translations/de.ts, packages/components/src/translations/en.ts, packages/components/src/utilities/localize.ts
Closes #1486
This PR addresses:
- Add `aria-invalid` attribute
- Screen reader announcement when a tag is removed
To solve TalkBack issue a new issue has been created: #1708
=> fix: improve sd select a11y [skip chromatic]

.changeset/stale-planets-rest.md, .vscode/settings.json, packages/docs/src/stories/components/icon.stories.ts, packages/docs/src/stories/docs/general/03-Installation.mdx, packages/docs/src/stories/docs/general/07-FAQ.mdx
fix typos and configure spell checker extension
=> fix: typos and configure spell checker extension [skip chromatic]

.changeset/warm-news-scream.md, packages/docs/.storybook/main.ts, packages/docs/package.json, packages/docs/scripts/storybook/docs-codepen-enhancer.ts
Makes it possible to test resulting Codepens on PRs and Pre-Releases.
=> chore: fix URLs in Codepens in dev Storybooks

.changeset/short-tools-prove.md
This PR is meant to corrrectly publish the styles package into npm.
=> chore: add changeset to publish styles package

.changeset/honest-drinks-help.md, .changeset/strange-baboons-carry.md, packages/components/src/components/tab/tab.ts, packages/docs/src/stories/components/tab.stories.ts, packages/docs/src/stories/components/tab.test.stories.ts
=> fix: sd-tab broken padding-right

.changeset/silent-knives-love.md, packages/components/src/components/flipcard/flipcard.test.ts, packages/components/src/components/flipcard/flipcard.ts
=> fix: improve sd-flipcard hidden side a11y

.changeset/tiny-items-sort.md, packages/components/src/components/combobox/combobox.test.ts
This PR addresses a failing test in the combobox placeholder text.
=> fix: combobox tests

.changeset/moody-toes-draw.md, packages/docs/src/stories/packages/components/Migration/from-v3.mdx
=> fix: use correct URLs in migration guide

.changeset/calm-rice-study.md, packages/docs/src/stories/packages/components/Migration/from-v3.mdx
=> fix: wrong URLs in migration guide

.changeset/silly-deers-crash.md, packages/components/src/internal/solid-element.ts
Fixes a problem reported on the Teams support channel.
=> fix: tailwind gradients not working

.changeset/stale-icons-breathe.md, .changeset/twelve-kids-develop.md, packages/components/src/components/tooltip/tooltip.test.ts, packages/components/src/components/tooltip/tooltip.ts, packages/docs/src/stories/components/tooltip.stories.ts
This PR closes [#1744](https://github.com/solid-design-system/solid/issues/1744) and [#1700](https://github.com/solid-design-system/solid/issues/1700)
=> fix: improve tooltip

.changeset/great-rockets-cross.md, .changeset/silent-bats-compete.md, packages/components/src/components/map-marker/map-marker.ts, packages/docs/src/stories/components/map-marker.stories.ts
Closes [1803](https://github.com/solid-design-system/solid/issues/1803)
=> fix: map marker shadow

.changeset/selfish-cats-complain.md, packages/components/src/components/checkbox-group/checkbox-group.test.ts, packages/components/src/components/checkbox-group/checkbox-group.ts, packages/components/src/components/input/input.test.ts, packages/components/src/components/input/input.ts, packages/components/src/components/radio-group/radio-group.test.ts, packages/components/src/components/radio-group/radio-group.ts, packages/components/src/components/select/select.test.ts, packages/components/src/components/select/select.ts, packages/components/src/components/textarea/textarea.test.ts, packages/components/src/components/textarea/textarea.ts
Closes [#1702 ](https://github.com/solid-design-system/solid/issues/1702)
=> fix: margin for input forms

.changeset/smart-buckets-punch.md, packages/docs/src/stories/docs/general/02-Accessibility.mdx
=> chore: update general accessibility docs

.changeset/smart-seas-cover.md, README.md, packages/docs/.storybook/test-runner.ts, packages/docs/package.json, packages/docs/scripts/test.js, packages/docs/scripts/vite-plugin-get-playwright-version.ts, packages/docs/src/stories/packages/docs/AccessibilityTests.mdx, pnpm-lock.yaml
=> fix: docs a11y tests errors [skip chromatic]

.changeset/curvy-houses-fix.md, .changeset/spicy-flies-ring.md, packages/components/src/components/checkbox/checkbox.test.ts, packages/components/src/components/checkbox/checkbox.ts, packages/docs/scripts/storybook/helper.ts, packages/docs/src/stories/components/checkbox.stories.ts, packages/docs/src/stories/components/checkbox.test.stories.ts
=> fix: sd-checkbox a11y issues

.changeset/fuzzy-rings-jump.md, .changeset/tasty-pigs-design.md, packages/components/src/components/video/video.ts, packages/components/src/translations/de.ts, packages/components/src/translations/en.ts, packages/components/src/utilities/localize.ts, packages/docs/src/stories/components/video.test.stories.ts
=> fix: sd-video a11y issues [skip chromatic]

.changeset/sixty-starfishes-check.md, packages/docs/src/stories/styles/interactive.stories.ts, packages/docs/src/stories/styles/interactive.test.stories.ts
=> fix: disable sd-interact a11y issue [skip chromatic]

.changeset/tasty-bobcats-peel.md, packages/docs/scripts/storybook/helper.ts, packages/docs/src/stories/components/brandshape.stories.ts, packages/docs/src/stories/components/brandshape.test.stories.ts
=> fix: sd-brandshape a11y issues

.changeset/legal-tables-tie.md, packages/docs/src/stories/templates/table.stories.ts
Closes [#1895](https://github.com/solid-design-system/solid/issues/1895)
=> fix: sd-table template a11y

.changeset/forty-experts-tie.md, .changeset/popular-boats-build.md, packages/components/src/components/input/input.test.ts, packages/components/src/components/input/input.ts, packages/components/src/translations/de.ts, packages/components/src/translations/en.ts, packages/components/src/utilities/localize.ts, packages/docs/src/stories/components/input.stories.ts, packages/docs/src/stories/components/input.test.stories.ts
Closes https://github.com/solid-design-system/solid/issues/1877
=> fix: sd input a11y issues

.changeset/six-otters-shave.md, packages/docs/src/stories/components/accordion-group.test.stories.ts, packages/docs/src/stories/templates/accordion-group.stories.ts
=> fix: sd-accordion a11y issues

.changeset/loud-chicken-wave.md, .changeset/thin-ways-confess.md, packages/components/src/components/step-group/step-group.ts, packages/components/src/components/step/step.test.ts, packages/components/src/components/step/step.ts, packages/docs/scripts/storybook/helper.ts, packages/docs/src/stories/components/step-group.stories.ts, packages/docs/src/stories/components/step-group.test.stories.ts, packages/docs/src/stories/components/step.stories.ts, packages/docs/src/stories/components/step.test.stories.ts, packages/docs/src/stories/templates/step-group.stories.ts
Closes https://github.com/solid-design-system/solid/issues/1894, closes https://github.com/solid-design-system/solid/issues/1884 and closes https://github.com/solid-design-system/solid/issues/1883
=> fix: sd-step, sd-step-group and sd-step group template a11y issues

.changeset/metal-countries-sort.md, .changeset/violet-students-hope.md, packages/components/src/components/map-marker/map-marker.test.ts, packages/components/src/components/map-marker/map-marker.ts, packages/docs/src/stories/components/map-marker.test.stories.ts
=> fix: sd-map-marker a11y issues [skip chromatic]

.changeset/cool-gorillas-wash.md, packages/docs/src/stories/components/dropdown.test.stories.ts
=> fix: sd-dropdown a11y issue

.changeset/empty-brooms-jump.md, packages/docs/src/stories/components/header.test.stories.ts
Closes [#1978](https://github.com/solid-design-system/solid/issues/1978)
=> fix: sd-header a11y

.changeset/lovely-scissors-remember.md, packages/docs/scripts/storybook/helper.ts, packages/docs/src/stories/styles/list.test.stories.ts
=> fix: sd-list and sd-prose a11y issues

.changeset/brown-lobsters-sing.md, .changeset/wise-months-exercise.md, packages/components/src/components/teaser/teaser.ts, packages/docs/scripts/storybook/helper.ts, packages/docs/src/stories/components/teaser.test.stories.ts
=> fix: sd-teaser a11y issues

.github/ISSUE_TEMPLATE/release-notes-subtask-template.md
In order to create these issues even faster:
- added issue type
- checked all DoR checkboxes
- removed placeholder from title
=> chore: Update release-notes-subtask-template.md [skip chromatic]

.changeset/selfish-bobcats-sneeze.md, packages/docs/src/stories/components/accordion-group.stories.ts, packages/docs/src/stories/styles/list.test.stories.ts, packages/docs/src/stories/styles/prose.test.stories.ts, packages/docs/src/stories/templates/audio.stories.ts, packages/docs/src/stories/templates/autocomplete.stories.ts
=> fix: unskip remaining a11y tests

.changeset/clever-ghosts-begin.md, packages/docs/src/stories/components/button.stories.ts, packages/docs/src/stories/components/link.stories.ts
Closes #1421
Direct link: https://solid-design-system.github.io/solid/docs_fix-button-link/?path=/docs/components-sd-button--docs#as-link
=> docs: 📚 describe link usage for sd-button

.github/workflows/check-pr.yml, .github/workflows/chromatic-main.yml, .github/workflows/chromatic-next.yml, .github/workflows/release-main.yml, .github/workflows/release-next.yml, .github/workflows/size-check.yml, .github/workflows/upload-storybook-to-github-pages.yml, README.md, package.json
Due to recurring problems when switching projects with different node/pnpm versions, this makes working easier and more robust.
=> chore: stick versions in package.json

.changeset/thin-laws-explode.md, packages/components/src/components/navigation-item/navigation-item.test.ts, packages/components/src/components/navigation-item/navigation-item.ts, packages/components/src/translations/de.ts, packages/components/src/translations/en.ts, packages/components/src/utilities/localize.ts
=> fix: sd-navigation-item a11y reaudit

.changeset/tiny-crabs-nail.md, packages/docs/src/stories/templates/pagination.stories.ts
=> fix: sd-pagination a11y re-audit

.changeset/new-months-leave.md, packages/docs/src/stories/templates/forms.stories.ts
=> fix: forms template a11y re-audit [skip chromatic]

.changeset/hungry-doors-relate.md, packages/docs/src/stories/templates/table.stories.ts
=> fix: table template a11y reaudit

.changeset/metal-eels-unite.md, .changeset/pink-clocks-build.md, packages/components/src/components/drawer/drawer.ts, packages/docs/src/stories/templates/drawer.stories.ts
=> fix: sd-drawer a11y reaudit

.changeset/red-spoons-teach.md, packages/docs/src/stories/templates/status-badge.stories.ts
Closes [#1852 ](https://github.com/solid-design-system/solid/issues/1852)
=> feat: status badge template

.changeset/lucky-camels-cut.md, packages/components/src/components/scrollable/scrollable.test.ts, packages/components/src/components/scrollable/scrollable.ts
=> fix!: sd-scrollable start and end events

.changeset/kind-ants-ask.md, packages/components/src/components/carousel/carousel.ts
Adresses one part of [#2187](https://github.com/solid-design-system/solid/issues/2197)
=> feat: carousel dots motion

.changeset/pretty-points-jump.md, .changeset/thirty-ants-read.md, packages/components/src/components/button/button.ts, packages/docs/src/stories/components/button.test.stories.ts
=> fix: icon-left slot alignment on sd-button

.changeset/cute-places-chew.md, .changeset/new-jars-lose.md, .changeset/shaggy-paws-wonder.md, packages/components/src/components/expandable/expandable.ts, packages/components/src/internal/animate.ts, packages/components/src/internal/solid-element.ts, packages/docs/src/stories/components/expandable.stories.ts, packages/docs/src/stories/components/expandable.test.stories.ts, packages/docs/src/stories/packages/components/Migration/from-v4.mdx, packages/docs/src/stories/templates/expandable.stories.ts, packages/styles/src/modules/interactive.css
=> feat: implement expandable motion design

.changeset/loose-cities-act.md, packages/components/src/components/map-marker/map-marker.ts, packages/components/tailwind.config.cjs
=> feat: implement map marker motion

.changeset/eight-ears-stay.md, .changeset/orange-pillows-hunt.md, packages/components/src/components/checkbox/checkbox.ts
Closes: https://github.com/solid-design-system/solid/issues/1826
=> feat: add motion design for sd-checkbox

.changeset/fifty-colts-sort.md, packages/components/src/internal/solid-element.ts
=> fix: token processor not processing

.changeset/nice-hounds-play.md, packages/components/src/components/map-marker/map-marker.ts
=> fix: adjust map-marker motion design angle

.changeset/wise-dingos-grow.md, packages/components/src/components/drawer/drawer.ts
=> fix: sd-drawer animation flickering

.changeset/swift-places-admire.md, packages/docs/src/stories/styles/list.stories.ts
This PR syncs the list orientation description with Figma
=> chore: update list orientation description

.changeset/free-loops-tease.md, packages/components/src/components/header/header.ts
=> fix: sd-header overritten padding bottom

.changeset/cute-impalas-argue.md, packages/docs/src/stories/components/breadcrumb-item.stories.ts, packages/docs/src/stories/components/icon.stories.ts, packages/docs/src/stories/components/option.stories.ts, packages/docs/src/stories/components/step.stories.ts, packages/docs/src/stories/components/tab.stories.ts, packages/docs/src/stories/styles/footnotes.stories.ts, packages/docs/src/stories/styles/interactive.stories.ts
=> fix: missing storybook docs

.changeset/vast-sites-go.md, packages/components/src/components/drawer/drawer.ts
=> fix: sd-drawer close button position rtl

.changeset/modern-jeans-peel.md, .changeset/yellow-flies-cheer.md, packages/docs/src/stories/styles/interactive.stories.ts, packages/docs/src/stories/styles/interactive.test.stories.ts, packages/styles/src/modules/interactive.css
=> fix: sd-interactive disabled color

.changeset/three-rings-deny.md, packages/docs/src/stories/components/tab.stories.ts
=> fix: tab active story issue after rejoining docs [skip chromatic]

.changeset/six-trams-bathe.md, packages/components/src/components/radio-group/radio-group.ts, packages/components/src/components/tab-group/tab-group.test.ts
=> fix: missing accessible name on the radio-group

.changeset/legal-gifts-show.md, packages/components/src/components/select/select.ts
=> fix: broken select popup horizontal scroll

.changeset/little-dolls-try.md, packages/components/src/components/tag/tag.test.ts, packages/components/src/components/tag/tag.ts
=> fix: disallow removable tag with href

.changeset/empty-rules-know.md, .changeset/itchy-cars-shake.md, packages/docs/src/stories/docs/general/05-Known Browser Issues.mdx, packages/docs/src/stories/styles/footnotes.mdx, packages/docs/src/stories/templates/footnotes.stories.ts, packages/styles/src/modules/footnotes.css
=> fix: footnotes anchor behaviour

.changeset/fine-donkeys-sit.md, packages/docs/src/stories/templates/button.stories.ts
=> fix: button template layout issue

packages/components/src/components/brandshape/brandshape.ts
=> fix: remove console log

.changeset/polite-jobs-show.md, packages/docs/src/stories/templates/step-group.stories.ts
=> fix: changed the id into class in horizontal inline template

.changeset/tame-clocks-shout.md, packages/docs/.storybook/test-runner.ts, packages/docs/src/stories/components/breadcrumb-item.stories.ts, packages/docs/src/stories/components/breadcrumb-item.test.stories.ts, packages/docs/src/stories/components/drawer.test.stories.ts, packages/docs/src/stories/components/header.test.stories.ts, packages/docs/src/stories/components/menu-item.stories.ts, packages/docs/src/stories/components/menu-item.test.stories.ts, packages/docs/src/stories/components/menu.test.stories.ts, packages/docs/src/stories/components/option.stories.ts, packages/docs/src/stories/components/option.test.stories.ts, packages/docs/src/stories/components/step-group.test.stories.ts, packages/docs/src/stories/components/step.stories.ts, packages/docs/src/stories/components/step.test.stories.ts, packages/docs/src/stories/components/tab-group.test.stories.ts, packages/docs/src/stories/components/tab.stories.ts, packages/docs/src/stories/components/tab.test.stories.ts, packages/docs/src/stories/packages/docs/AccessibilityTests.mdx, packages/docs/src/stories/styles/footnotes.stories.ts, packages/docs/src/stories/styles/interactive.stories.ts, packages/docs/src/stories/styles/interactive.test.stories.ts, packages/docs/src/stories/styles/pagination.test.stories.ts, packages/docs/src/stories/templates/footnotes.stories.ts
Closes [#2468](https://github.com/solid-design-system/solid/issues/2468)
=> fix: a11y tests

packages/docs/.storybook/addons/manager.ts, packages/docs/.storybook/addons/theme-generator/Panel.tsx, packages/docs/.storybook/addons/theme-generator/constants.ts, packages/docs/.storybook/addons/theme-generator/preview.ts, packages/docs/.storybook/addons/theme-generator/withGlobals.ts, packages/docs/scripts/vite-plugin-get-tailwind-theme.ts, packages/theming/src/color-calculation.js, packages/theming/src/get-theme-colors.js, packages/tokens/scripts/build.mjs, packages/tokens/src/theme.mjs
=> feat: reimplement theme generator
