solid-design-system/solid

- packages/components/src/components/accordion-group/accordion-group.ts
- packages/components/src/components/accordion/accordion.ts
Fixed styles in sd-accordion to only show focus border during keyboard navigation / tabbed browsing / sr usage.
Changed the status of sd-accordion-group from experimental to stable.
> fix: 🤔 sd-accordion focus state

- packages/components/src/styles/paragraph/paragraph.css
Changed the default size of the paragraph component to 16px(text-base) instead of the initial 20px. (text-lg). Closes #406 
> fix: 🤔changed paragraph default size to text-base

- packages/components/src/components/teaser/teaser.test.ts
- packages/components/src/components/teaser/teaser.ts
Fixed a bug in sd-teaser to prevent rewrite of inset property when changing variants and added a corresponding test for it. Closes #362 
> fix: 🐛 prevent rewrite of inset property when border variant was selected in sd-teaser

- CONTRIBUTING.md
Added a subchapter on our guidance over using //TODO comments in code.  Closes https://github.com/solid-design-system/solid/issues/389
> docs: 📚 update contribution guide - //TODOs 

- CONTRIBUTING.md
- packages/components/.storybook/preview-head.html
- packages/components/src/components/accordion-group/accordion-group.stories.ts
- packages/components/src/components/accordion/accordion.stories.ts
- packages/components/src/components/badge/badge.stories.ts
- packages/components/src/components/brandshape/brandshape.stories.ts
- packages/components/src/components/drawer/drawer.stories.ts
- packages/components/src/components/dropdown/dropdown.stories.ts
- packages/components/src/components/navigation-item/navigation-item.stories.ts
- packages/components/src/components/tag/tag.stories.ts
- packages/components/src/components/teaser/teaser.stories.ts
Replaces all instances of slot-comp in our repository and added a bullet point explaining usage of slots . Closes #359
> docs: 📚 housekeeping – align slots

- renovate.json
Removed redundant rule to update dev dependencies that also auto-merged major updates, added blanked rule to turn off automerge for major updates. Closes  #497
> ci: 👷 stop major updates from automerging

- CONTRIBUTING.md
Section about handling PRs in our Project has been added.
Closes https://github.com/solid-design-system/internal/issues/45
> docs: add pr handling section to contribution.md

- packages/components/.storybook/addons/theme-generator/Panel.tsx
- packages/components/.storybook/addons/theme-generator/colorCalculations.ts
- packages/components/.storybook/addons/theme-generator/constants.ts
- packages/components/.storybook/addons/theme-generator/withGlobals.ts
In some occasions, some primary colors went dark when using the tokens creator. This PR should overcome this problem and in general uses a more understandable approach how to calculate the colors.
> docs: prevent primary colors going black

- packages/components/src/components/accordion-group/accordion-group.stories.ts
- packages/components/src/components/accordion-group/accordion-group.ts
- packages/components/src/components/accordion/accordion.ts
- packages/components/src/components/carousel/carousel.stories.ts
sd-accordion refresh. Closes #407.
> feat: ✨ update sd-accordion meeting WCAG criteria / design refresh

- .github/workflows/lint-pr.yml
- CONTRIBUTING.md
Removed refactor from the pr-lint allowed semantic terms. Closes #533. 
> ci: 👷 refine PR title linting

- packages/components/src/solid-styles.css
- packages/components/src/styles/container/container.css
- packages/components/src/styles/container/container.declaration.ts
- packages/components/src/styles/container/container.stories.ts
Added sd-container. Closes #271.
> feat: ✨ add sd-container - CSS style

- .github/workflows/check-pr.yml
- .github/workflows/size-check.yml
closes #580 
After lots of trial and error, this works now:
1. As long as we're in draft mode, all actions are skipped.
2. As soon as it switches to reviewable, all actions start to run.
> chore: 🔧 add draft-check job to PRs

- packages/components/src/styles/chip/chip.css
Because there were no examples yet when merging the sd-chip story, it was not noticed that the sd-chip wraps the text with long content.
Go to storybook sd-chip -> Chip Samples add long content to sd-chip
> fix: 🤔 sd-chip prevent text wrap

- packages/components/src/docs/Migration/ui-input.mdx
Description
Sd-input migration guide from the respective ui-component (Component Library) to our SDS Component.
As the CL component has been reduced a lot and split up into several SDS components, multiple migrations guides are necessary :
ui-input to sd-input
ui-input to sd-radio
ui-input to sd-switch
ui-input to sd-checkbox
Closes #603 
DoD
> docs: 📚 add migration guide for sd-input

- packages/components/src/components/teaser/teaser.ts
Added negative margin on the media slot in the teaser variant 'white border-neutral-400' so that it overlaps the border and matches the design.
> fix: 🤔 teaser variant 'white border-neutral-400', - no border around media slot

- .github/workflows/check-pr.yml
- packages/components/package.json
- packages/components/src/components/checkbox/checkbox.stories.ts
- packages/components/src/components/checkbox/checkbox.test.ts
- packages/components/src/components/checkbox/checkbox.ts
- packages/components/src/components/input/input.stories.ts
- packages/components/src/components/input/input.test.ts
- packages/components/src/components/input/input.ts
- packages/components/src/components/radio-group/radio-group.stories.ts
- packages/components/src/components/radio-group/radio-group.test.ts
- packages/components/src/components/radio-group/radio-group.ts
- packages/components/src/components/select/select.stories.ts
- packages/components/src/components/select/select.test.ts
- packages/components/src/components/select/select.ts
- packages/components/src/internal/form.ts
- pnpm-lock.yaml
It should not be needed that users interact with an input element to show an error message, if setCustomValidity('an error') and reportValidity() was called. Before that the user needed to interact with the element, to show the error or make it valid.
---
The draft PR currently only contains rough tests, which describe more or less the actual behaviour. Plus a Storybook story was created which shows a demo. (Clicking on a button should directly show the validation.)
> fix: 🐛 make setCustomValidity() + reportValidity() work with inputs' inline errors

- packages/components/src/components/select/select.stories.ts
- packages/components/src/components/select/select.ts
> fix: 🤔 parts not marked (red border) in storybook in sd-select

- packages/components/src/components/carousel/carousel.test.ts
Closes #387. I noticed it takes a moment for the `aria-busy` attribute to be updated after scrollend is fired. I added a 100ms timeout to account for that gap.
https://github.com/solid-design-system/solid/assets/63849626/a0d8b7ca-1883-4a24-90ef-667648c6daca
> chore: 🔧 fix failing scrollend event related tests for sd-carousel [skip chromatic]

- packages/theming/src/color-calculation.js
currently the white and black color doesn't get transforemd from hex to rgb value.
This pr converts the white and black color to the rbg format like the other colors
> fix: output of color-calculation.js for white and black color

- CONTRIBUTING.md
adding a section to the contribution guide, which explains the idea and rules for an optional feature-check-in meeting, in order to prepare pull requests. 
closes #613
> docs: add feature-check-in section to contribution guide [skip chromatic]

- .github/pull_request_template.md
- CONTRIBUTING.md
- added a section into the contribution guide, to describe the rules on how we want to comment on PRs.
- removed unnecessary checkbox from PR-template.
closes #614
> docs: add review comment section to guidelines [skip chromatic]

- packages/tokens/src/tokens.json
due to the deprecation of sd-quote [#572](https://github.com/solid-design-system/solid/issues/572), all gradients applied for this component should be deprecated: 
-gradient.horizontal-transparent-black|75
-gradient.horizontal-black|75-transparent
-gradient.horizontal-transparent-white|80
-gradient.horizontal-white|80-transparent
-gradient.horizontal-black|80-black|65
-gradient.horizontal-black|65-black|80
Todos after FE's approval:
> fix: remove unneeded gradient horizontal

- packages/components/src/styles/container/container.css
- packages/components/src/styles/container/container.declaration.ts
- packages/components/src/styles/container/container.stories.ts
closes #737 
The ticket defines a custom css property "triangle-background" which sets the background color of the triangle cut out.  I don't see another "style" that demonstrates the use of a "css property" (I know for components this can be documented in the comment block at the top of the component file), so I am not sure how to document that properly and include it in the Triangle story.  Please advise.
> feat: ✨ add sd container triangle property

- packages/tokens/src/tokens.json
following #300 00
adjusting gradient tokens due to change in build from color gradient fill to masking gradient fill. 
vertical-transparent-white token is adjusted and kept for sd-expandable
vertical-white-transparent is deprecated
> fix: adjusting vertical-transparent-white token + deprecating vertical-white-transparent

- packages/components/src/components/tab-group/tab-group.stories.ts
- packages/components/src/components/tab-group/tab-group.ts
Closes [#866](https://github.com/solid-design-system/solid/issues/865) and [#865](https://github.com/solid-design-system/solid/issues/865). Some general optimisations of the docs included (removing unnecessary iframes).
> docs: 📚 add sd-tab-group samples that do not show the custom css & remove deprecated css properties

- packages/components/src/components/header/header.stories.ts
Fix a broken path for the logo in Sample B Story of the sd-header.
Closes #807
> fix: 🤔 logo for the Sample B Story of the sd-header

- packages/components/src/components/tab-group/tab-group.stories.ts
- packages/components/src/components/tab/tab.stories.ts
- packages/components/src/components/tab/tab.ts
> fix: 🤔 tabs do not grow with longer tab titles 

- packages/components/src/components/navigation-item/navigation-item.test.ts
- packages/components/src/components/navigation-item/navigation-item.ts
> fix: 🐛 sd-navigation-item remove default href + href when children

- packages/tokens/src/tokens.json
following #300 & [#168](https://github.com/solid-design-system/figma/issues/168)
since expandable's gradient is reworked into with masking. These tokens are no longer valid and need to be deprecated at releasing: 
-gradient.horizontal-white-transparent
-gradient.horizontal-transparent-white
-gradient.vertical-transparent-white
-gradient.vertical-transparent-primary
this token needs to be released:
-gradient.vertical-white-transparent
> ci(token): sd-expandable deprecating old gradient tokens

- packages/components/src/components/icon/icon.stories.ts
adds a disclaimer to the sd-icon docs in order to make clear, icons are not provided or maintained by Solid Design System Team.
closes #939
> docs: add provider disclaimer to sd-icon docs

- .github/pull_request_template.md
as metadata is not working in pr-templates, the seetings have been added as comments
> ci: replace PR template metadata with comments [skip chromatic]

- packages/components/scripts/node-version-components.cjs
This excludes event names from versioning. 
Before that the event `sd-input` was renamed to `sd-2-11-0-input`. This came from the fact, that the event had the same name as a component. This change omits this.
> fix: exclude event names from versioning

- packages/tokens/src/tokens.json
link to ticket #963 
following [#573](https://github.com/solid-design-system/solid/issues/573)
closes #573 
shadow-md was created from the style importing from the old sketch file. 
Since in the new design, it's visually sufficient for the map marker to consume the shadow token, this token is no longer valid and need to be deprecated at releasing
> ci(token): add *background-transparent|30 token for sd-map-marker

- packages/components/src/patterns/autocomplete/autocomplete.stories.ts
- packages/components/src/utilities/autocomplete-config.test.ts
- packages/components/src/utilities/autocomplete-config.ts
This optimizes the DOM structure created by the `autocomplete-config` to allow `max-height`. In addition this improves a11y as a `ul` is now used as wrapper.
> feat: ✨ optimize `autocomplete-config` to allow max-height for listbox

- .github/workflows/check-pr.yml
- DEVELOPER_STARTING_GUIDE.md
- renovate.json
I added a preset to carry out only security updates. I also removed a lot of redundant config that was already covered by presets. Closes #914.
> ci: stop non-security renovate updates [skip chromatic] 

- packages/tokens/src/tokens.json
following #300 & #289, old gradients used for sd-scrollable V.0.0.1 & sd-expandable V.0.0.1 must be deprecated:
-gradient.vertical-white-transparent
-gradient.horizontal-transparent-white
-gradient.horizontal-white-transparent
-gradient.vertical-transparent-white
-gradient.vertical-transparent-primary
> ci(token): deprecating old gradient tokens for sd-expandable & sd-scrollable

- packages/components/src/styles/table-cell/table-cell.stories.ts
This fixes a bug in FireFox 115.11.0esr that did hide borders when `position: sticky` is set on an element. This will be solved in a future ESR version and therefore is only implemented in the pattern and not in the `sd-table` itself. Furthermore some redundant TailwindCSS classes were removed.
> docs: fix firefox bug in table cell example (close #911)

- packages/components/package.json
- packages/components/scripts/node-optimize-chromatic.cjs
- packages/components/src/patterns/autocomplete/autocomplete.stories.ts
- packages/components/src/utilities/autocomplete-config.ts
Enables to import utilities. This solves to easily import e. g. `autocomplete-config` without having to point to the direct path via `node_modules/@solid-design-system/...`.
Everything was tested locally:
> fix: add utilities to exports

- packages/components/tailwind.config.cjs
Current bug:
This was not apparent in Storybook, as for Storybook we provide more CSS at all.
Fix shows that class is now part of published CSS:
> fix: add missing tailwind classes

- packages/tokens/src/tokens.json
following #1013 
4 color tokens need to be added for sd-flipcard:
gradient.vertical-white|75-white|60 
gradient.vertical-white|60-transparent
gradient.vertical-primary-800|75-primary-800|60
gradient.vertical-primary-800|60-transparent
> ci(token): add 4 gradients for sd-flipcard [skip chromatic]

- packages/components/src/components/input/input.stories.ts
- packages/components/src/components/input/input.test.ts
- packages/components/src/components/input/input.ts
- packages/components/src/internal/solid-element.ts
input type - date : min and max properties (of type type of string) was added so that type of input:Date can also use those properties.
> feat: 🎸 adding min and max posibility for date type of input

- packages/components/src/components/tooltip/tooltip.test.ts
- packages/components/src/components/tooltip/tooltip.ts
If the tooltip trigger is set to `click focus`, the focus event will be triggered first and the attached logic will run. Afterwards, the logic of the `click`event will also run, meaning that the tooltip will open and close immediately. In this PR we add a flag that will control which of the event handle should be executed.
> fix: sd-tooltip self closing with click focus trigger (close #1211)

- packages/components/src/components/input/input.ts
- packages/components/src/components/select/select.ts
Change "clear button' color in sd-input and sd-select from neutral-500 to neutral-800.
Change "valid input" text color from green to default text color for accessibility.
> fix: #1193 correct clear button color in sd-icon and sd-select

- packages/components/src/components/link/link.test.ts
- packages/components/src/components/link/link.ts
> fix: pass empty download attr to "a" tag in sd-link

- packages/components/.storybook/preview-head.html
Similar to the behaviour of the components will hide the "default" story preventing to have it duplicated to styles.
> feat: hide first default story in styles [skip chromatic]

- packages/components/.storybook/preview.js
Testable on sd-prose → last sample
Old: https://solid-design-system.github.io/solid/main/?path=/docs/styles-sd-prose--docs
New: https://solid-design-system.github.io/solid/docs_fix-wrong-code-preview/?path=/docs/styles-sd-prose--docs
> docs: fix code previews for strings (closes #1264) [skip chromatic]

- packages/components/src/components/navigation-item/navigation-item.stories.ts
- packages/components/src/components/navigation-item/navigation-item.test.ts
- packages/components/src/components/navigation-item/navigation-item.ts
Ticket for [#344](https://github.com/orgs/solid-design-system/projects/1/views/54?pane=issue&itemId=55679158).
Added _separated_ property. When true, instead of summary and details, two divs will be rendered, containing a sd-link and a sd-button.
> feat: ✨ enable usage of link with children on sd-navigation-item

- packages/components/src/components/textarea/textarea.ts
neutral-100 background style was overridden by the bg-white. Now neutral-100 is always applied when readonly is true.
> fix: neutral-100 should apply on readonly textarea

- packages/components/src/components/input/input.ts
Fixed Background Color for read-only state.
> fix: correct readonly background styles for sd-input

- packages/components/src/components/input/input.ts
- packages/components/src/components/select/select.ts
- packages/components/src/components/textarea/textarea.ts
Closes #1172. Removed the valid/invalid text-color from input fields and replaced it with text-black.
> fix: 🤔 correct colors in form field validation 

- packages/components/src/styles/display/display.css
- packages/components/src/styles/display/display.declaration.ts
- packages/components/src/styles/display/display.stories.ts
The default size variant in code is now changed to 4xl. 
Closes https://github.com/solid-design-system/solid/issues/1355.
> fix: 🤔 sd-display main size variant

- packages/components/src/components/step/step.test.stories.ts
- packages/components/src/components/step/step.ts
`sd-divider` was replaced with borders, as otherwise an `hr` would have been announced.
> fix: make sd-step-group more accessible

- packages/components/src/components/select/select.test.stories.ts
- packages/components/src/components/select/select.ts
Limited the height of the listbox using an interesting CSS variable I found in the wrapping sd-popup :) 
`--auto-size-available-height`. Closes #1042.
> fix: 🤔 missing border when sd-select has not enough space 

- packages/components/src/components/textarea/textarea.test.stories.ts
- packages/components/src/components/textarea/textarea.ts
The textarea now takes the full height of it's container. Closes #719.
> fix: 🤔 sd-textarea doesn't accept full height of container

- packages/components/src/styles/copyright/copyright.css
- packages/components/src/styles/copyright/copyright.declaration.ts
- packages/components/src/styles/copyright/copyright.stories.ts
Created now a vertical variant for sd-copyright and marked horizontal as default.
Closes https://github.com/solid-design-system/solid/issues/1319.
> feat: ✨ add vertical variant to sd-copyright

- packages/components/src/components/carousel/autoplay-controller.ts
- packages/components/src/components/carousel/carousel.stories.ts
- packages/components/src/components/carousel/carousel.test.ts
- packages/components/src/components/carousel/carousel.ts
I updated the autoplay behaviour to make it consistent with user expectations. I additionally added a blur on the resume button to make the the autoplay resumes as soon the button is clicked. (It needed the user to manually click somewhere else to start). 
@coraliefeil @MartaPintoTeixeira I added some code-only documentation to the Autoplay story. This needs to be agreed on and aligned with the Figma docs. 
Closes #1250.
> fix: 🤔 pause not working in sd-carousel

- packages/components/src/components/notification/notification.stories.ts
As discussed in our daily, I added some information in the notification.
> docs: add a11y warning for sd-notification [skip chromatic]

- packages/components/src/templates/interactive.stories.ts
Add an accessible name to the icon-only interactive button in the `sd-interactive` template to improve accessibility for users who rely on screen readers.
> fix: sd-interactive a11y template 

- DEVELOPER_STARTING_GUIDE.md
As a new joined developer on the SDS team, I would like to see an updated version of the `DEVELOPER_STARTING_GUIDE.md`.
This PR addresses some outdated documentation on the developer starting guide.
Section regarding a `demo-project` has been removed since it redirects to a 404 page and hasn't been updated for a long time.
> docs: update developer starting guide [skip chromatic]

- packages/components/src/components/switch/switch.test.ts
- packages/components/src/components/switch/switch.ts
Close #1488
Goals:
Note: While testing using a screen reader, before replacing the role to `switch`, it would read as `on tick box` or `off tick box`. After replacing the role, it now reads as `on switch` or `off switch`. Since it reads out as `switch`, the user assumes it has only 2 possible states, which is true.
> fix: improve sd-switch a11y

- packages/components/src/components/tag/tag.test.ts
- packages/components/src/components/tag/tag.ts
- packages/docs/src/stories/components/tag.stories.ts
- packages/docs/src/stories/templates/tag.stories.ts
Closes #1490
Goal: Implement `aria-pressed` on the sd-tag and a `toggleable` attribute to control whenever the `aria-pressed` should show or not.
> fix: improve sd-tag a11y

- packages/components/src/components/notification/notification.ts
- packages/components/src/components/tab-group/tab-group.ts
- packages/components/src/styles/table-cell/table-cell.css
This PR removes the usage of bg-neutral-400 from the codebase. It's required before merging [1671](https://github.com/solid-design-system/solid/pull/1671)
> chore: replace usage of bg-neutral-400 with border-neutral-400

- .changeset/happy-pumas-travel.md
- packages/components/src/styles/flag/flag.css
Closes https://github.com/solid-design-system/solid/issues/1611 and https://github.com/solid-design-system/solid/issues/1530
> fix: sd-flag improve a11y

- .changeset/eight-bats-roll.md
- packages/components/src/components/dropdown/dropdown.ts
- packages/components/src/components/navigation-item/navigation-item.ts
- packages/components/src/internal/tabbable.ts
- packages/docs/src/stories/components/dropdown.stories.ts
- packages/docs/src/stories/templates/dropdown.stories.ts
Closes #1516 #1475 
This PR addresses:
- Correctly label icon-button dropdown triggers.
- Fix focus on the trigger after the dropdown is hidden using the keyboard.
> fix: improve sd-dropdown a11y

- .changeset/ninety-yaks-mix.md
- packages/components/src/components/divider/divider.test.ts
- packages/components/src/components/divider/divider.ts
Closes #1497 
This PR addresses:
- Implement `aria-orientation` on sd-divider
> fix: improve sd-divider a11y

- .changeset/tiny-walls-joke.md
- packages/components/src/components/tab-group/tab-group.ts
This PR was created coming from a bug that was described in MS Teams. It replicated the changes from Shoelace: https://github.com/shoelace-style/shoelace/blob/6761fdceca3bfa7d5f78097c30db0a9cfbd88d6f/src/components/tab-group/tab-group.component.ts#L142
It is hard to create a test for this, that's why this was omitted.
> fix: fix disconnecedCallback in sd-tab-group

- .changeset/poor-beers-rule.md
- packages/docs/src/stories/styles/hidden-links.stories.ts
- packages/docs/src/stories/styles/hidden-links.test.stories.ts
Closes #1505 
This PR addresses:
- sd-hidden-links behind header due to z-index issue on screenshot test.
- added debug attribute to show sd-hidden-links on screenshot test.
> fix: sd-hidden-links screenshot tests

- .changeset/pretty-bears-kneel.md
- packages/components/src/components/combobox/combobox.test.ts
- packages/components/src/components/combobox/combobox.ts
- packages/components/src/components/select/select.test.ts
- packages/components/src/components/select/select.ts
This PR addresses the missing translation of the input placeholder in the sd-select and sd-combobox components and closes [#998](https://github.com/solid-design-system/solid/issues/998)
> fix: reactive translations

- .changeset/silent-goats-unite.md
- packages/docs/scripts/storybook/docs-codepen-enhancer.ts
This PR fixes the urls in `docs-codepen-enhancer` so that the correct files are loaded within the Codepen editor.
It also includes a small refactor of the urls logic to improve readability.
> fix: codepen urls

- .changeset/plenty-tigers-begin.md
- packages/components/src/components/combobox/combobox.test.ts
- packages/components/src/components/combobox/combobox.ts
- packages/components/src/components/select/select.test.ts
- packages/components/src/components/select/select.ts
This PR adds reactive translation to the `maxOptionsTagLabel` attribute of the `sd-select` and `sd-combobox` components.
> fix: tags selected translation

- .github/ISSUE_TEMPLATE/feature-issue-template.md
Subtask section is not needed anymore. Github now offers a built-in feature to link parent and subtasks.
> ci: Update feature-issue-template [skip chromatic]

- .changeset/thin-stingrays-glow.md
- packages/docs/src/stories/packages/eslint-plugin/Changelog.mdx
- packages/docs/src/stories/packages/eslint-plugin/Index.mdx
This PR adds the docs for `eslint-plugin` package, which was not addressed in the other PR #1864.
Related to #1735
> feat: add eslint-plugin docs [skip chromatic]

- .changeset/beige-glasses-glow.md
- packages/components/src/components/dialog/dialog.ts
This PR sets the dialog panel max-height and prevents panel elements from collapsing or overflowing when the component is displayed in high zoom level (400%).
> fix: dialog height

- .github/ISSUE_TEMPLATE/release-notes-subtask-template.md
added a new template to easily setup subtasks every iteration
new setup:
- #1923 will be the never-ending-parent-epic-task with 0 SP, assigned to @yoezlem and always "in progress"
- each iteration we create a new subtask with this template
this follows the way, our dependancy dashboard works but there we have a bot from renovate taking care of reopening it each time.
> chore: add release notes subtask template [skip chromatic]

- .changeset/long-balloons-study.md
- packages/components/src/components/audio/audio.test.ts
- packages/components/src/components/audio/audio.ts
- packages/components/src/translations/de.ts
- packages/components/src/translations/en.ts
- packages/components/src/utilities/localize.ts
This PR addresses an issue with the progress bar syncronization, aria-attributes incorrectly set and also closes [#1869](https://github.com/solid-design-system/solid/issues/1869)
> fix: sd-audio a11y

- .changeset/pink-buses-obey.md
- .changeset/sour-nails-fold.md
- packages/components/src/components/radio-group/radio-group.ts
- packages/docs/src/stories/components/radio-button.test.stories.ts
- packages/docs/src/stories/components/radio-group.stories.ts
- packages/docs/src/stories/components/radio-group.test.stories.ts
- packages/docs/src/stories/components/radio.stories.ts
- packages/docs/src/stories/components/radio.test.stories.ts
> fix: sd-radio, sd-radio-group and sd-radio-button a11y issues

- .changeset/huge-ducks-spend.md
- packages/docs/src/stories/components/badge.test.stories.ts
- packages/docs/src/stories/templates/badge.stories.ts
Closes [#1891 ](https://github.com/solid-design-system/solid/issues/1891)
> fix: sd-badge template a11y

- .changeset/fruity-needles-own.md
- .changeset/hip-peas-pick.md
- packages/components/src/components/optgroup/optgroup.ts
- packages/components/src/translations/de.ts
- packages/components/src/translations/en.ts
- packages/components/src/utilities/localize.ts
- packages/docs/src/stories/components/optgroup.stories.ts
- packages/docs/src/stories/components/optgroup.test.stories.ts
Closes [#1879 ](https://github.com/solid-design-system/solid/issues/1879)
> fix: sd-optgroup a11y

- .changeset/curvy-buckets-buy.md
- packages/docs/src/stories/components/combobox.stories.ts
- packages/docs/src/stories/components/combobox.test.stories.ts
Closes [#1875 ](https://github.com/solid-design-system/solid/issues/1875)
@MartaPintoTeixeira in the `icons` story I had to include labels. Please sync with Figma. Thank you
> fix: sd-combobox a11y

- .changeset/spicy-plants-burn.md
- packages/docs/src/stories/components/dialog.test.stories.ts
- packages/docs/src/stories/templates/dialog.stories.ts
Closes [#1892](https://github.com/solid-design-system/solid/issues/1892), closes #1893
> fix: sd-dialog template a11y

- .changeset/stale-shoes-sparkle.md
- packages/docs/src/stories/components/carousel.test.stories.ts
During our latest sd-carousel PRs, a screenshot test regression has been overlooked. This PR fixes that issue.
> fix: sd-carousel screenshot test regression

- .changeset/lemon-sloths-sort.md
- packages/docs/src/stories/components/video.stories.ts
Unskips a11y tests and adds missing alt attribute
> fix: sd-video a11y

- .changeset/yummy-clouds-fix.md
- packages/docs/src/stories/components/scrollable.test.stories.ts
Unskips a11y tests and adds missing label
> fix: sd-scrollable a11y

- .changeset/wide-hands-clean.md
- packages/docs/src/stories/components/textarea.test.stories.ts
Closes [#1981](https://github.com/solid-design-system/solid/issues/1981)
> fix: sd-textarea a11y

- .changeset/twenty-rules-invent.md
- packages/docs/src/stories/components/select.test.stories.ts
Closes [#1983](https://github.com/solid-design-system/solid/issues/1983)
> fix: sd-select a11y

- .changeset/purple-comics-wink.md
- packages/styles/src/modules/copyright.css
- packages/styles/src/solid-styles.css
This PR fixes the shadow of `sd-copyright` which was not rendering due to missing variables.
The issue is only visible outside of storybook (eg: codepen) and was reported in the support channel.
> fix: sd-copyright shadow not rendering

- .changeset/sweet-onions-prove.md
- packages/components/src/components/button/button.ts
- packages/docs/src/stories/components/button.stories.ts
- packages/docs/src/stories/components/button.test.stories.ts
Closes [#2049](https://github.com/solid-design-system/solid/issues/2049)
> fix: sd-button a11y reaudit

- .changeset/spotty-apples-share.md
- packages/components/src/components/input/input.ts
Closes [#2054](https://github.com/solid-design-system/solid/issues/2054)
> fix: sd-input a11y reaudit

- .changeset/late-hotels-glow.md
- packages/components/src/components/select/select.ts
This PR addresses a property that was missed when tackling this [ticket](https://github.com/solid-design-system/solid/issues/2082).
> fix: reflect missing attributes

- .changeset/eighty-kiwis-cough.md
- packages/components/src/components/step/step.ts
This PR fixes an issue with the not-interactive step when user browsers font minimum size is set.
To test: 
- go to [sd-step-group](https://solid-design-system.fe.union-investment.de/docs/?path=/docs/components-sd-step-group--docs#not-interactive-1)
- In safari > settings > advanced > accessibility > tick "never use font sizes smaller than" > set it to 32
Current behaviour:
Fixed version:
> fix: not interactive step min font size

- .changeset/true-meals-join.md
- packages/docs/scripts/storybook/helper.ts
This PR is a continuation of the improvements made in [#2082](https://github.com/solid-design-system/solid/issues/2082).
With this transformation, we remove `=""` from attributes. This is needed to prevent giving the incorrect information to users when clicking "show code" in storybook stories. This is also transformed in codepen.
Current behaviour (see inverted attribute):
Expected behaviour (see inverted attribute):
> fix: boolean properties in storybook

- .changeset/fine-planets-study.md
- .changeset/rare-mice-boil.md
- .changeset/silly-gifts-cut.md
- .changeset/three-roses-agree.md
- .changeset/true-peas-pump.md
- packages/components/CONTRIBUTING.md
- packages/components/src/components/audio/audio.ts
- packages/components/src/components/combobox/combobox.ts
- packages/components/src/components/dialog/dialog.test.ts
- packages/components/src/components/dialog/dialog.ts
- packages/components/src/components/drawer/drawer.test.ts
- packages/components/src/components/drawer/drawer.ts
- packages/components/src/components/dropdown/dropdown.ts
- packages/components/src/components/expandable/expandable.ts
- packages/components/src/components/input/input.ts
- packages/components/src/components/navigation-item/navigation-item.ts
- packages/components/src/components/notification/notification.ts
- packages/components/src/components/quickfact/quickfact.ts
- packages/components/src/components/radio/radio.ts
- packages/components/src/components/scrollable/scrollable.ts
- packages/components/src/components/select/select.ts
- packages/components/src/components/step/step.ts
- packages/components/src/components/tab-group/tab-group.ts
- packages/components/src/components/tag/tag.ts
- packages/components/src/components/textarea/textarea.ts
- packages/components/src/components/tooltip/tooltip.ts
- packages/components/src/components/video/video.ts
- packages/components/src/internal/deep-active-element.ts
Closes #2066 
- Improve focus management for elements within ShadowDOMs triggering sd-dialog and sd-drawer.
- Ensure sd-input supports password autofill.
- Update the type of the containingElement property in sd-dropdown.
- Fix component dependencies, so that needed components are automatically imported.
- Adjust aria-label for playback speed to reflect the current speed value.
> fix: 🐛 sd-audio a11y and other things

- .changeset/early-lies-pull.md
- packages/docs/src/stories/styles/list.test.stories.ts
- packages/styles/src/modules/list.css
We had to update the styling of the list, as `display: table` changed the semantics of it.
This led to several updates.
1. For ordered lists we used the `::marker` pseudo class to define ordered sublevels (e. g. `1.1.1`), instead of hacking around with `::before` etc. Unfortunately this is not fully supported in Safari (https://bugs.webkit.org/show_bug.cgi?id=204163, https://developer.mozilla.org/en-US/docs/Web/CSS/::marker). Therefore we fallback there to showing it as `1.`.
2. We had to refine the paddings etc. This chance was used to bring development closer to the Figma design.
Everything was tested with Safari, Edge and Firefox.
<!-- *PR notes: Irrelevant elements should be removed.* -→
<!-- *If this PR includes a bug fix, an E2E test is necessary to verify the change. If the fix is …
> fix: 🐛 fix a11y for sd-list

- .changeset/brave-cups-check.md
- packages/styles/src/modules/pagination.css
Pagination arrow styles were being applied based on the existence of `sd-icon`. This would break when using versioned components, such as `<sd-4-8-0-icon>`. 
This PR fixes that issue.
[Codepen with issue](https://codepen.io/paulovareiro29/pen/RNPPNmB)
> fix: add support for pagination versioned icons

- .changeset/eleven-groups-arrive.md
- packages/styles/CHANGELOG.md
- packages/styles/package.json
Last December when the styles package was first released, the initial version was set to 1.4.0 by mistake. It was unpublished from NPM but since it's there, now that the real 1.4.0 needed to be released, it's not possible. This PR bumps the package version to 1.4.1 to ensure the release on NPM and also adds this information to the changelog.
> fix: styles package npm release

- .changeset/spicy-gifts-share.md
- packages/docs/src/stories/docs/general/01-Introduction.mdx
- removed section on sept. '24 update on the introduction page
- rephrased component, style and template description in order to match with figma texts
- closes #2348
> docs: update introduction page [skip chromatic]

- .changeset/huge-beers-hang.md
- packages/components/src/components/expandable/expandable.ts
Steps for testing:
- Go to the `sd-expandable` inverted story.
- Override on the DOM the following variables: `--gradient-color-start` and `--gradient-color-end` to `rgba(45, 157, 0, 0)` and `rgba(45, 157, 0, 1)` respectively.
- On production, the gradient doesn't change color. On this PR it does.
Closes #1299
> fix: make expandable inverted fit to theme

- .changeset/warm-webs-check.md
- packages/components/src/components/checkbox/checkbox.ts
This PR fixes an issue with the `sd-checkbox` animation that was not displaying the `indeterminate` icon.
> fix: checkbox indeterminate
